name: appointments
description: "Appointments Project"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  # Core
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  path: ^1.9.0
  intl: ^0.19.0

  # Architecture
  get: ^4.6.6
  injector: ^3.0.0

  # Storage
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  sqlite3: ^2.4.2

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  gap: ^3.0.1

dev_dependencies:
  # Core
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0

  # Storage
  drift_dev: ^2.16.0

  # Generators
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
